//  node:util module supports the needs of Node.js internal APIs
const util = require('util');
const fs = require('fs');

// UUID v1 is generated by using a combination the host computers MAC address and the current date and time
const uuidv1 = require('uuid/v1'); 

// promisfy() converts callback-based functions to promise-based functions
const readFileAsync = util.promisify(fs.readFile);
const writeFileAsync = util.promisify(fs.writeFile);

class Store {
    read(){
        return readFileAsync('db/db.json', 'utf8');
    }

    write(note){
        return writeFileAsync('db/db.json', JSON.stringify(note))
    }

    getNotes() {
        return this.read().then((notes)=>{
            let parsedNotes;
            try {
                parsedNotes = [].concat(JSON.parse(notes))
            } catch(err){
                parsedNotes = []
            }
            return parsedNotes;
        })
    }
}